baseURL: "https://lalu-sz.github.io/lalu_sz_/" 
title: La_Lu_Sz
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Portfolio
          url: /portfolio/
          weight: 1
        - name: CV
          url: /CV/
          weight: 2
        - name: CV
          url: /CV/
          weight: 3        


params:
    description: "Digital. Urban. Geospatial. Cartography. (Dis)ability."
    author: Laurel Sparks
    googleAnalyticsID: "G-97G4MZ4061"
    DateFormat: "Spring 2024"
    defaultTheme: dark
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Laurel Sparks
          subtitle: "Digital. Urban. Geospatial. Cartography. (Dis)ability."
          imageUrl: "prof_pic.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Laurel Sparks
          buttons:
            - name: Portfolio
              url: /portfolio/
            - name: Publications
              url: /publications/
            - name: CV
              url: /CV/

    socialIcons:
        - name: CV
          url: "\CV_Sparks.pdf"
        - name: Email
          url: mailto:sparkslaurel@gmail.com
        - name: University of Kentucky
          url: /location/
        - name: Contact
          url: /officehours/
        - name: GitHub
          url: https://github.com/lalu-sz

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Laurel Sparks"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2